spring.application.name=demo
server.port=5050

# Fabric Network Configuration
fabric.channelName = mychannel
fabric.chaincodeName = caac
fabric.mspId = Org1MSP

fabric.cryptoPath = ${CAAC_FABRIC_CRYPTO_PATH:/home/meeoree/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com}

# Endpoint of the Org1 Peer
fabric.peerEndpoint = localhost:7051
fabric.peerOverrideAuthority = peer0.org1.example.com
